version: "3.9"
services:
  animales:
    build: .
    ports:
      - "3000:3000"
    links:
      - monguito
  monguito:
    image: mongo
    ports:
      - "8001:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rafa
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
volumes: 
  mongo-data: 

